library(dplyr)
library(lubridate)
Sys.setenv("LANGUAGE"="En")
Sys.setlocale("LC_ALL", "English")

dat <- read.table('C:/Users/usuario/Desktop/household_power_consumption.txt', header = TRUE, sep = ';', stringsAsFactors = FALSE)
dat$Date <- as.Date(dat$Date, format = "%d/%m/%Y")
dat2 <- subset(dat, Date == "2007-02-01" | Date == "2007-02-02")
dat2 <- dat2 %>% mutate(DH = paste(as.character(Date), as.character(Time), sep = " ")) 
dat2$DH <- strptime(dat2$DH, format = "%Y-%m-%d %H:%M:%S", tz = 'GMT')
dat2$Sub_metering_1 <- as.numeric(dat2$Sub_metering_1)
dat2$Sub_metering_2 <- as.numeric(dat2$Sub_metering_2)
dat2$Sub_metering_3<- as.numeric(dat2$Sub_metering_3)
dat2$Global_active_power <- as.numeric(dat2$Global_active_power)
dat2$Voltage <- as.numeric(dat2$Voltage)

png(file = "plot1.png", width = 480, height = 480)
hist(dat2$Global_active_power, xlab = "Global Active Power (Kilowatts)", ylab = "Frecuency", main = 'Global Active Power', freq = TRUE, col = "red" )
dev.off()